language: python
python: "3.7"
before_install:
	- pip3 install tox-travis flask flask-login tox flask-wtf
	#- pip3 -r requirements.txt

script:
	- flask run &
	- tox # -< easy integration with python
	
	