language: python
python: 
    -"2.7"
    -"3.6"
install:
    - pip3 install requests tox-travis flask flask-login tox flask-wtf BeautifulSoup4 bs4
    - pip install requests tox-travis flask flask-login tox flask-wtf BeautifulSoup4 bs4

script:
    - flask run &
    - tox 
