language: python
#python: "3.6"
install:
    - pip3 install requests tox-travis flask flask-login tox flask-wtf BeautifulSoup4 bs4
    - pip install requests tox-travis flask flask-login tox flask-wtf BeautifulSoup4 bs4

matrix:
    include:
    - python: 2.7
        env:
        - TOX_ENV=py27
    - python: 3.6
        env: 
        - TOX_ENV=py36

script:
    - flask run &
    - tox -e $TOX_ENV
